# These are supported funding model platforms

ko_fi: masdenk # Replace with a single Ko-fi username
custom: ["https://www.buymeacoffee.com/masdenk", "https://www.paypal.com/donate/?cmd=_donations&business=XM9RU544JWTYU"]
